### ISSUE TITLE
Directions for building and deploying the RI

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#37]
We need to create a "getting started" doc that explains:
- [ ] source artifacts (folders, script, etc.)
- [ ] how to provision using the scripts
- [ ] how to build the source
- [ ] how to run the sample

**Comment by bennage** [comment]
@lbrader provide an outline for @JohnPWSharp

**Comment by lbrader** [comment]
Added outline yesterday.  Working on the validation section with Streaming Analytic's and Hive Query

**Comment by JohnPWSharp** [comment]
I have a couple of initial comments from writing a step-by-step guide for building and deploying the code:

1. IMHO it is inadvisable to provide default values for the service bus namespace (fabrikam-ns01) and the storage account (fabrikamstorage01) because they could cause clashes (they are used to generate URLs so they need to be unique)

2.  Provisioning the event hub (Provision-EventHub.ps1) fails. The CreateEventHubIfNotExists seems to fall over (it retries several times before giving up). I have tried creating the event hub manually first (eventhub01) but the script still falls over at this point.

**Comment by JohnPWSharp** [comment]
Additional information about the failure in CreateEventHubIfNotExists. If you try running the script enough times, it eventually succeeds! (is there a timing issue?)

**Comment by bennage** [comment]
opened #65 per @JohnPWSharp's recommendation.

**Comment by lbrader** [comment]
updated @JohnPWSharp   updated larry/doc-provision-run/build-deploy-iot.md validation sections using Streaming Analytics and Hive query.

**Comment by JohnPWSharp** [comment]
Provisioning the event hub seems to work today (it times out at most once with a 401 Unauthorized exception but works ok on retry). I guess something was just feeling a little off-colour yesterday!

**Comment by bennage** [comment]
Yay! (I think.)
